apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: my-django-app:v1  # Replace with your registry image if using a remote registry
          ports:
            - containerPort: 8000
          #env:
           # - name: DJANGO_SETTINGS_MODULE
            #  value: "todo_app.settings"  # Update if required
