apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080  # Exposes the app on port 30080 of the node
  type: NodePort
